kind: pipeline
name: default
steps:
- name: docker
  image: plugins/docker
  settings:
    registry: git.jbranan.com
    dry_run: false
    username: jblu
    password: 
      from_secret: gittea_drone
    repo: git.jbranan.com/jblu/qbit-maid
    tags:
    - latest
  when:
    branch:
      - main
    event:
      - push
      - pull_request
- name: docker-test
  image: plugins/docker
  settings:
    registry: git.jbranan.com
    dry_run: false
    username: jblu
    password: 
      from_secret: gittea_drone
    repo: git.jbranan.com/jblu/qbit-maid
    tags:
    - dev
  when:
    branch:
      - dev*
    event:
      - push
      - pull_request
- name: test-main
  image: git.jbranan.com/jblu/qbit-maid:latest
  commands:
  - python test_qbitmaid.py
  - python test_dragnet.py
  when:
    branch:
      - main
    event:
      - push
      - pull_request
- name: test-dev
  image: git.jbranan.com/jblu/qbit-maid:dev
  commands:
  - python test_qbitmaid.py
  - python test_dragnet.py
  when:
    branch:
      - dev*
    event:
      - push
      - pull_request