kind: pipeline
name: default

steps:
- name: docker
  image: plugins/docker
  settings:
    registry: git.jbranan.com
    dry_run: false
    username: jblu
    password: 
      from_secret: gittea_drone
    repo: git.jbranan.com/jblu/qbit-maid
    tags:
    - latest
  when:
    branch:
      - main
- name: docker-test
  image: plugins/docker
  settings:
    registry: git.jbranan.com
    dry_run: false
    username: jblu
    password: 
      from_secret: gittea_drone
    repo: git.jbranan.com/jblu/qbit-maid
    tags:
    - dev
  when:
    branch:
      - dev*